In [1]:
import pandas as pd 
import numpy as np

In [2]:
#IMPORTING DATASET
df=pd.read_csv('customer_shopping_behavior.csv')

In [3]:
df.sample(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
2594,2595,59,Male,Skirt,Clothing,81,Montana,L,Indigo,Fall,3.6,No,Free Shipping,No,No,25,Cash,Every 3 Months
1867,1868,45,Male,Skirt,Clothing,52,Delaware,M,Brown,Fall,3.4,No,2-Day Shipping,No,No,20,Venmo,Quarterly
1751,1752,57,Male,Sweater,Clothing,40,Ohio,M,Silver,Winter,3.2,No,2-Day Shipping,No,No,34,Cash,Annually
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly
2463,2464,60,Male,Blouse,Clothing,21,Mississippi,XL,Indigo,Summer,3.3,No,Standard,No,No,25,Cash,Bi-Weekly
2630,2631,29,Male,Skirt,Clothing,82,Maine,S,Pink,Spring,4.2,No,Free Shipping,No,No,20,Cash,Quarterly
2744,2745,38,Female,Shirt,Clothing,66,Wyoming,M,Silver,Winter,3.3,No,Store Pickup,No,No,40,Credit Card,Monthly
247,248,29,Male,Sweater,Clothing,66,Montana,XL,Brown,Spring,4.4,Yes,Standard,Yes,Yes,14,Debit Card,Weekly
3595,3596,21,Female,Blouse,Clothing,41,South Dakota,M,Violet,Spring,3.1,No,Store Pickup,No,No,14,PayPal,Annually
1702,1703,54,Male,Jeans,Clothing,83,Alabama,XL,Yellow,Summer,5.0,No,Express,No,No,48,Bank Transfer,Weekly

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [5]:
# df.describe(include="all")
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [7]:
# df['Review Rating']=df['Review Rating'].fillna(df['Review Rating'].mode()[0]
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [8]:
# colms name changing
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(" ","_")
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [9]:
#  create age groups 
labels=['Young Adult','Adult','Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [10]:
df[['age','age_group']].sample(10)

      age    age_group
2557   70       Senior
1165   51  Middle-aged
3819   36        Adult
3216   39        Adult
2189   38        Adult
53     29  Young Adult
947    57  Middle-aged
421    38        Adult
3782   40        Adult
753    47  Middle-aged

In [11]:
df.sample(4)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group
2430,2431,20,Male,Jacket,Outerwear,100,North Dakota,XL,White,Summer,4.3,No,Express,No,No,42,Cash,Quarterly,Young Adult
94,95,58,Male,Skirt,Clothing,76,Nevada,S,Silver,Spring,4.6,Yes,Free Shipping,Yes,Yes,28,Credit Card,Weekly,Senior
827,828,31,Male,Shoes,Footwear,51,Colorado,S,Green,Fall,4.1,Yes,Free Shipping,Yes,Yes,33,Bank Transfer,Fortnightly,Young Adult
2716,2717,47,Female,Shoes,Footwear,40,Colorado,L,Black,Spring,2.7,No,Store Pickup,No,No,21,Debit Card,Weekly,Middle-aged

In [12]:
# create colmn purchase_frequency_days 
freq_mapping={
    'Weekly': 7,
    'Bi-Weekly': 14,
    'Fortnightly': 14,
    'Monthly': 30,
    'Every 3 Months':90,
    'Quarterly': 90,
    'Annually':365
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(freq_mapping)

In [13]:
df[['purchase_frequency_days','frequency_of_purchases']].sample(5)

      purchase_frequency_days frequency_of_purchases
1472                        7                 Weekly
2408                       90         Every 3 Months
3206                       30                Monthly
3536                       30                Monthly
598                        90         Every 3 Months

In [14]:
# df[['discount_applied','promo_code_used']].sample(5)
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [15]:
df=df.drop('promo_code_used',axis=1)
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [16]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\victus\anaconda3\envs\campusx\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\victus\anaconda3\envs\campusx\lib\site-packages (2.0.44)
Requirement already satisfied: greenlet>=1 in c:\users\victus\anaconda3\envs\campusx\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\victus\anaconda3\envs\campusx\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
from sqlalchemy import create_engine
# Step 1: Your PostgreSQL details
username = "postgres"       # default username
password = "1234"           # tumhara password
host = "localhost"          # same machine
port = "5432"               # default PostgreSQL port
database = "customer_behavior"  # tumhara database name

# Step 2: Create Engine (connection string)
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 3: Load Dataframe into PostgreSQL
table_name = "customers"   # any table name

df.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customers' in database 'customer_behavior'.